'use client';

import React, { useState } from 'react';
import { Sparkles, Send, Plane, ShieldCheck, MapPin, Loader2, Bot } from 'lucide-react';

export const AiAdvisor: React.FC = () => {
  const [destination, setDestination] = useState('Japan');
  const [days, setDays] = useState(10);
  const [budgetUsd, setBudgetUsd] = useState(2500);
  const [travelerType, setTravelerType] = useState('Sightseeing & Food');
  const [phoneModel, setPhoneModel] = useState('iPhone 15 Pro');
  const [question, setQuestion] = useState('');
  const [loading, setLoading] = useState(false);
  const [advice, setAdvice] = useState<string | null>(null);

  const handleGenerate = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    setLoading(true);
    setAdvice(null);

    try {
      const res = await fetch('/api/gemini/advisor', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          destination,
          days,
          budgetUsd,
          travelerType,
          phoneModel,
          question,
        }),
      });

      const data = await res.json();
      if (res.ok && data.advice) {
        setAdvice(data.advice);
      } else {
        setAdvice(data.error || 'Unable to generate advice at this moment.');
      }
    } catch (err: any) {
      setAdvice('Connection error. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const quickPresets = [
    { label: 'AI Travel Plan for Japan', dest: 'Japan', days: 10, budget: 2500 },
    { label: 'Dubai / UAE Cash Guide', dest: 'United Arab Emirates', days: 5, budget: 1500 },
    { label: 'Pakistan Family Visit', dest: 'Pakistan', days: 14, budget: 1000 },
    { label: 'USA Shopping & Tech Trip', dest: 'United States', days: 7, budget: 3000 },
  ];

  return (
    <div id="ai-advisor" className="py-8">
      <div className="bg-[#14171F] border border-slate-800 rounded-3xl p-6 sm:p-8 shadow-2xl relative overflow-hidden">
        {/* Glow */}
        <div className="absolute -right-20 -top-20 w-80 h-80 bg-teal-500/10 blur-[90px] pointer-events-none rounded-full" />

        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
          <div>
            <div className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-teal-400 bg-teal-950 px-2.5 py-1 rounded-md border border-teal-800/60 mb-2">
              <Sparkles className="w-3.5 h-3.5" />
              <span>AI Travel & Currency Expert</span>
            </div>
            <h2 className="text-2xl sm:text-3xl font-black text-white">
              AI Travel Currency & eSIM Advisor
            </h2>
            <p className="text-xs text-slate-300 mt-1 max-w-xl">
              Get personalized cash vs card recommendations, local tipping rules, and phone eSIM advice generated by Gemini AI for your trip.
            </p>
          </div>

          {/* Presets */}
          <div className="flex items-center gap-2 overflow-x-auto pb-1">
            {quickPresets.map((p) => (
              <button
                key={p.label}
                onClick={() => {
                  setDestination(p.dest);
                  setDays(p.days);
                  setBudgetUsd(p.budget);
                }}
                className="px-3 py-1.5 rounded-xl text-xs font-bold bg-[#0F1115] hover:bg-slate-800 border border-slate-700/80 text-slate-300 transition-all shrink-0 flex items-center gap-1.5"
              >
                <span>{p.label}</span>
              </button>
            ))}
          </div>
        </div>

        <form onSubmit={handleGenerate} className="grid grid-cols-1 md:grid-cols-12 gap-4 mb-6">
          <div className="md:col-span-3">
            <label className="block text-xs font-bold text-slate-400 mb-1">Destination Country</label>
            <input
              type="text"
              value={destination}
              onChange={(e) => setDestination(e.target.value)}
              className="w-full py-2.5 px-3 bg-[#0F1115] border border-slate-700/80 rounded-xl text-xs font-bold text-white focus:outline-none focus:border-teal-400"
              placeholder="e.g. Japan, Turkey, UAE"
              required
            />
          </div>

          <div className="md:col-span-2">
            <label className="block text-xs font-bold text-slate-400 mb-1">Trip Days</label>
            <input
              type="number"
              value={days}
              onChange={(e) => setDays(parseInt(e.target.value) || 1)}
              className="w-full py-2.5 px-3 bg-[#0F1115] border border-slate-700/80 rounded-xl text-xs font-bold text-white focus:outline-none focus:border-teal-400"
              min="1"
            />
          </div>

          <div className="md:col-span-3">
            <label className="block text-xs font-bold text-slate-400 mb-1">Budget ($ USD / £ GBP)</label>
            <input
              type="number"
              value={budgetUsd}
              onChange={(e) => setBudgetUsd(parseInt(e.target.value) || 100)}
              className="w-full py-2.5 px-3 bg-[#0F1115] border border-slate-700/80 rounded-xl text-xs font-bold text-white focus:outline-none focus:border-teal-400"
            />
          </div>

          <div className="md:col-span-4">
            <label className="block text-xs font-bold text-slate-400 mb-1">Your Phone Model</label>
            <input
              type="text"
              value={phoneModel}
              onChange={(e) => setPhoneModel(e.target.value)}
              className="w-full py-2.5 px-3 bg-[#0F1115] border border-slate-700/80 rounded-xl text-xs font-bold text-white focus:outline-none focus:border-teal-400"
              placeholder="e.g. iPhone 15 Pro, Galaxy S24"
            />
          </div>

          <div className="md:col-span-12">
            <label className="block text-xs font-bold text-slate-400 mb-1">Specific Question or Notes (Optional)</label>
            <div className="flex gap-2">
              <input
                type="text"
                value={question}
                onChange={(e) => setQuestion(e.target.value)}
                className="w-full py-2.5 px-3 bg-[#0F1115] border border-slate-700/80 rounded-xl text-xs text-white focus:outline-none focus:border-teal-400"
                placeholder="e.g. Do small shops accept credit cards? Is eSIM supported on my phone?"
              />
              <button
                type="submit"
                disabled={loading}
                className="px-6 py-2.5 bg-teal-500 hover:bg-teal-400 disabled:opacity-50 text-slate-950 font-black text-xs rounded-xl transition-all shrink-0 flex items-center gap-1.5 shadow-lg"
              >
                {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
                <span>{loading ? 'Analyzing...' : 'Generate Plan'}</span>
              </button>
            </div>
          </div>
        </form>

        {advice && (
          <div className="mt-6 p-5 sm:p-6 rounded-2xl bg-[#0B0D12] border border-teal-900/60 space-y-3 text-xs sm:text-sm text-slate-200 leading-relaxed animate-in fade-in duration-300">
            <div className="flex items-center gap-2 pb-3 border-b border-slate-800 text-teal-300 font-extrabold text-sm">
              <Bot className="w-4 h-4 text-teal-400" />
              <span>AI Travel Advisor Analysis for {destination}</span>
            </div>
            <div className="whitespace-pre-wrap font-sans text-slate-300 space-y-2">
              {advice}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
