import { Currency, StoreBranch } from './types';

export const INITIAL_CURRENCIES: Currency[] = [
  {
    code: 'USD',
    name: 'US Dollar',
    flag: 'https://flagcdn.com/w80/us.png',
    marketRate: 1.305,
    sellRate: 1.2946,
    buyRate: 1.3285,
    change24h: 0.14,
    popular: true,
  },
  {
    code: 'EUR',
    name: 'Euro',
    flag: 'https://flagcdn.com/w80/eu.png',
    marketRate: 1.185,
    sellRate: 1.1743,
    buyRate: 1.204,
    change24h: -0.06,
    popular: true,
  },
  {
    code: 'AED',
    name: 'UAE Dirham',
    flag: 'https://flagcdn.com/w80/ae.png',
    marketRate: 4.79,
    sellRate: 4.752,
    buyRate: 4.886,
    change24h: 0.08,
    popular: true,
  },
  {
    code: 'PKR',
    name: 'Pakistani Rupee',
    flag: 'https://flagcdn.com/w80/pk.png',
    marketRate: 364.5,
    sellRate: 362.68,
    buyRate: 373.61,
    change24h: 0.42,
    popular: true,
  },
  {
    code: 'CAD',
    name: 'Canadian Dollar',
    flag: 'https://flagcdn.com/w80/ca.png',
    marketRate: 1.785,
    sellRate: 1.7672,
    buyRate: 1.8207,
    change24h: -0.12,
    popular: true,
  },
  {
    code: 'AUD',
    name: 'Australian Dollar',
    flag: 'https://flagcdn.com/w80/au.png',
    marketRate: 1.982,
    sellRate: 1.9622,
    buyRate: 2.0216,
    change24h: 0.25,
    popular: true,
  },
  {
    code: 'TRY',
    name: 'Turkish Lira',
    flag: 'https://flagcdn.com/w80/tr.png',
    marketRate: 43.8,
    sellRate: 43.14,
    buyRate: 45.11,
    change24h: -0.55,
    popular: true,
  },
  {
    code: 'SAR',
    name: 'Saudi Riyal',
    flag: 'https://flagcdn.com/w80/sa.png',
    marketRate: 4.88,
    sellRate: 4.841,
    buyRate: 4.978,
    change24h: 0.03,
    popular: true,
  },
  {
    code: 'INR',
    name: 'Indian Rupee',
    flag: 'https://flagcdn.com/w80/in.png',
    marketRate: 109.8,
    sellRate: 108.7,
    buyRate: 112.22,
    change24h: 0.18,
    popular: true,
  },
  {
    code: 'JPY',
    name: 'Japanese Yen',
    flag: 'https://flagcdn.com/w80/jp.png',
    marketRate: 198.5,
    sellRate: 196.71,
    buyRate: 202.47,
    change24h: -0.28,
    popular: true,
  },
  {
    code: 'CHF',
    name: 'Swiss Franc',
    flag: 'https://flagcdn.com/w80/ch.png',
    marketRate: 1.152,
    sellRate: 1.1428,
    buyRate: 1.1727,
    change24h: 0.11,
    popular: false,
  },
  {
    code: 'THB',
    name: 'Thai Baht',
    flag: 'https://flagcdn.com/w80/th.png',
    marketRate: 46.2,
    sellRate: 45.65,
    buyRate: 47.36,
    change24h: 0.35,
    popular: false,
  },
  {
    code: 'SGD',
    name: 'Singapore Dollar',
    flag: 'https://flagcdn.com/w80/sg.png',
    marketRate: 1.745,
    sellRate: 1.731,
    buyRate: 1.7764,
    change24h: 0.05,
    popular: false,
  },
  {
    code: 'NZD',
    name: 'New Zealand Dollar',
    flag: 'https://flagcdn.com/w80/nz.png',
    marketRate: 2.18,
    sellRate: 2.156,
    buyRate: 2.2258,
    change24h: -0.19,
    popular: false,
  },
  {
    code: 'BDT',
    name: 'Bangladeshi Taka',
    flag: 'https://flagcdn.com/w80/bd.png',
    marketRate: 154.2,
    sellRate: 153.12,
    buyRate: 157.59,
    change24h: 0.22,
    popular: false,
  },
  {
    code: 'PHP',
    name: 'Philippine Peso',
    flag: 'https://flagcdn.com/w80/ph.png',
    marketRate: 74.8,
    sellRate: 74.05,
    buyRate: 76.67,
    change24h: 0.15,
    popular: false,
  },
];


export const STORE_BRANCHES: StoreBranch[] = [
  {
    id: 'glasgow-main',
    name: 'Glasgow Main Counter Hub',
    address: '22 Maxwell Road, Glasgow, G41 1QE, United Kingdom',
    phone: '+44 141 266 0379',
    hours: 'Mon-Fri 8am-9pm | Sat 8am-8pm | Sun 10am-6pm',
    isAirport: false,
    queueWaitTime: '< 3 mins',
    googleMapsUrl: 'https://maps.google.com/?q=22+Maxwell+Road,+Glasgow,+G41+1QE',
    features: [
      '0% Commission Foreign Notes',
      'Unlocked Smartphone Store',
      'Instant Phone Cash Trade-In',
      'eSIM Instant Voucher Terminal',
    ],
  },
];
