import { Currency, StoreBranch } from './types';

export const INITIAL_CURRENCIES: Currency[] = [
  {
    code: 'USD',
    name: 'US Dollar',
    flag: 'https://flagcdn.com/w80/us.png',
    buyRate: 1.305,
    sellRate: 1.282,
    change24h: 0.12,
    popular: true,
  },
  {
    code: 'EUR',
    name: 'Euro',
    flag: 'https://flagcdn.com/w80/eu.png',
    buyRate: 1.192,
    sellRate: 1.171,
    change24h: -0.08,
    popular: true,
  },
  {
    code: 'AED',
    name: 'UAE Dirham',
    flag: 'https://flagcdn.com/w80/ae.png',
    buyRate: 4.79,
    sellRate: 4.68,
    change24h: 0.05,
    popular: true,
  },
  {
    code: 'PKR',
    name: 'Pakistani Rupee',
    flag: 'https://flagcdn.com/w80/pk.png',
    buyRate: 364.5,
    sellRate: 356.2,
    change24h: 0.45,
    popular: true,
  },
  {
    code: 'CAD',
    name: 'Canadian Dollar',
    flag: 'https://flagcdn.com/w80/ca.png',
    buyRate: 1.785,
    sellRate: 1.742,
    change24h: -0.15,
    popular: true,
  },
  {
    code: 'AUD',
    name: 'Australian Dollar',
    flag: 'https://flagcdn.com/w80/au.png',
    buyRate: 1.982,
    sellRate: 1.935,
    change24h: 0.22,
    popular: true,
  },
  {
    code: 'TUR',
    name: 'Turkish Lira',
    flag: 'https://flagcdn.com/w80/tr.png',
    buyRate: 43.8,
    sellRate: 41.5,
    change24h: -0.65,
    popular: true,
  },
  {
    code: 'SAR',
    name: 'Saudi Riyal',
    flag: 'https://flagcdn.com/w80/sa.png',
    buyRate: 4.88,
    sellRate: 4.75,
    change24h: 0.02,
    popular: true,
  },
  {
    code: 'INR',
    name: 'Indian Rupee',
    flag: 'https://flagcdn.com/w80/in.png',
    buyRate: 109.8,
    sellRate: 106.5,
    change24h: 0.18,
    popular: true,
  },
  {
    code: 'JPY',
    name: 'Japanese Yen',
    flag: 'https://flagcdn.com/w80/jp.png',
    buyRate: 198.5,
    sellRate: 192.8,
    change24h: -0.32,
    popular: true,
  },
  {
    code: 'CHF',
    name: 'Swiss Franc',
    flag: 'https://flagcdn.com/w80/ch.png',
    buyRate: 1.152,
    sellRate: 1.128,
    change24h: 0.11,
    popular: false,
  },
  {
    code: 'THB',
    name: 'Thai Baht',
    flag: 'https://flagcdn.com/w80/th.png',
    buyRate: 46.2,
    sellRate: 44.5,
    change24h: 0.35,
    popular: false,
  },
];

export const STORE_BRANCHES: StoreBranch[] = [
  {
    id: 'glasgow-main',
    name: 'Glasgow Main Counter Hub',
    address: '22 Maxwell Road, Glasgow, G41 1QE, United Kingdom',
    phone: '+44 141 266 0379',
    hours: 'Mon-Fri 8am-9pm | Sat 8am-8pm | Sun 10am-6pm',
    isAirport: false,
    queueWaitTime: '< 3 mins',
    googleMapsUrl: 'https://maps.google.com/?q=22+Maxwell+Road,+Glasgow,+G41+1QE',
    features: [
      '0% Commission Foreign Notes',
      'Unlocked Smartphone Store',
      'Instant Phone Cash Trade-In',
      'eSIM Instant Voucher Terminal',
    ],
  },
];
