import { Currency, StoreBranch } from './types';

// Base currency is USD ($)
export const INITIAL_CURRENCIES: Currency[] = [
  {
    code: 'EUR',
    name: 'Euro',
    flag: '🇪🇺',
    symbol: '€',
    buyRate: 0.9180,
    sellRate: 0.9320,
    midRate: 0.9250,
    change24h: 0.34,
    popular: true,
    region: 'Europe',
  },
  {
    code: 'GBP',
    name: 'British Pound',
    flag: '🇬🇧',
    symbol: '£',
    buyRate: 0.7810,
    sellRate: 0.7950,
    midRate: 0.7880,
    change24h: -0.18,
    popular: true,
    region: 'Europe',
  },
  {
    code: 'JPY',
    name: 'Japanese Yen',
    flag: '🇯🇵',
    symbol: '¥',
    buyRate: 152.40,
    sellRate: 155.80,
    midRate: 154.10,
    change24h: -0.62,
    popular: true,
    region: 'Asia-Pacific',
  },
  {
    code: 'CAD',
    name: 'Canadian Dollar',
    flag: '🇨🇦',
    symbol: 'CA$',
    buyRate: 1.3780,
    sellRate: 1.3990,
    midRate: 1.3885,
    change24h: 0.12,
    popular: true,
    region: 'Americas',
  },
  {
    code: 'AUD',
    name: 'Australian Dollar',
    flag: '🇦🇺',
    symbol: 'A$',
    buyRate: 1.5120,
    sellRate: 1.5380,
    midRate: 1.5250,
    change24h: 0.45,
    popular: true,
    region: 'Asia-Pacific',
  },
  {
    code: 'CHF',
    name: 'Swiss Franc',
    flag: '🇨🇭',
    symbol: 'CHF',
    buyRate: 0.8810,
    sellRate: 0.8960,
    midRate: 0.8885,
    change24h: -0.08,
    popular: false,
    region: 'Europe',
  },
  {
    code: 'AED',
    name: 'UAE Dirham',
    flag: '🇦🇪',
    symbol: 'AED',
    buyRate: 3.6650,
    sellRate: 3.6820,
    midRate: 3.6730,
    change24h: 0.01,
    popular: true,
    region: 'Middle East',
  },
  {
    code: 'SAR',
    name: 'Saudi Riyal',
    flag: '🇸🇦',
    symbol: 'SAR',
    buyRate: 3.7420,
    sellRate: 3.7610,
    midRate: 3.7510,
    change24h: 0.02,
    popular: true,
    region: 'Middle East',
  },
  {
    code: 'SGD',
    name: 'Singapore Dollar',
    flag: '🇸🇬',
    symbol: 'S$',
    buyRate: 1.3320,
    sellRate: 1.3510,
    midRate: 1.3415,
    change24h: -0.25,
    popular: true,
    region: 'Asia-Pacific',
  },
  {
    code: 'INR',
    name: 'Indian Rupee',
    flag: '🇮🇳',
    symbol: '₹',
    buyRate: 85.90,
    sellRate: 87.80,
    midRate: 86.85,
    change24h: -0.15,
    popular: true,
    region: 'Asia-Pacific',
  },
  {
    code: 'PKR',
    name: 'Pakistani Rupee',
    flag: '🇵🇰',
    symbol: 'PKR',
    buyRate: 277.50,
    sellRate: 281.20,
    midRate: 279.35,
    change24h: 0.08,
    popular: true,
    region: 'Asia-Pacific',
  },
  {
    code: 'CNY',
    name: 'Chinese Yuan',
    flag: '🇨🇳',
    symbol: '¥',
    buyRate: 7.1850,
    sellRate: 7.2750,
    midRate: 7.2300,
    change24h: 0.19,
    popular: false,
    region: 'Asia-Pacific',
  },
  {
    code: 'MXN',
    name: 'Mexican Peso',
    flag: '🇲🇽',
    symbol: 'Mex$',
    buyRate: 19.80,
    sellRate: 20.45,
    midRate: 20.125,
    change24h: 0.52,
    popular: false,
    region: 'Americas',
  },
  {
    code: 'THB',
    name: 'Thai Baht',
    flag: '🇹🇭',
    symbol: '฿',
    buyRate: 34.20,
    sellRate: 35.10,
    midRate: 34.65,
    change24h: -0.31,
    popular: false,
    region: 'Asia-Pacific',
  },
  {
    code: 'TRY',
    name: 'Turkish Lira',
    flag: '🇹🇷',
    symbol: '₺',
    buyRate: 35.80,
    sellRate: 36.90,
    midRate: 36.35,
    change24h: -1.15,
    popular: false,
    region: 'Europe',
  }
];

export const STORE_BRANCHES: StoreBranch[] = [
  {
    id: 'b1',
    name: 'Glasgow Flagship Exchange Hub',
    address: '22 Maxwell Road, Glasgow, G41 1QE, UK',
    phone: '+44 1412660379',
    hours: '8:00 AM - 9:00 PM (Mon - Sat)',
    queueWaitTime: '1 - 3 mins',
    currencyInStock: ['All 15+ Currencies', 'High Volume Notes', 'Gold Bullion'],
    features: ['VIP Trading Lounge', 'Phone Trade-in Counter', 'Repair Lab', 'eSIM Kiosk'],
    isAirport: false,
    lat: 55.8433,
    lng: -4.2651,
    googleMapsUrl: 'https://maps.google.com/?q=22+Maxwell+Road+Glasgow+G41+1QE+UK',
  },
  {
    id: 'b2',
    name: 'Glasgow Airport Express Counter',
    address: 'International Departures Terminal, Glasgow Airport (GLA), Paisley PA3 2SW, UK',
    phone: '+44 1412660379',
    hours: '24 Hours / 7 Days',
    queueWaitTime: '2 - 5 mins',
    currencyInStock: ['USD', 'EUR', 'GBP', 'JPY', 'AED', 'CAD', 'AUD', 'SAR'],
    features: ['24/7 Service', 'Vault Express Pickup', 'SIM Card Activation', 'Unlocked iPhones'],
    isAirport: true,
    lat: 55.8643,
    lng: -4.4318,
    googleMapsUrl: 'https://maps.google.com/?q=Glasgow+Airport+International+Departures',
  },
  {
    id: 'b3',
    name: 'Glasgow Central Station Counter',
    address: 'Main Concourse Arcade #12, Glasgow Central Station, Gordon St, Glasgow G1 3SL',
    phone: '+44 1412660379',
    hours: '7:00 AM - 10:00 PM Daily',
    queueWaitTime: '3 - 8 mins',
    currencyInStock: ['USD', 'EUR', 'GBP', 'CAD', 'JPY', 'MXN', 'INR', 'PKR'],
    features: ['Express Foreign Notes', 'Fast Charging Accessories', 'Unlocked Smartphones'],
    isAirport: false,
    lat: 55.8591,
    lng: -4.2581,
    googleMapsUrl: 'https://maps.google.com/?q=Glasgow+Central+Station+Gordon+St',
  },
  {
    id: 'b4',
    name: 'Buchanan Galleries Glasgow Branch',
    address: 'Ground Floor, Tech & Travel Zone, Buchanan Galleries, 220 Buchanan St, Glasgow G1 2FF',
    phone: '+44 1412660379',
    hours: '10:00 AM - 8:00 PM Daily',
    queueWaitTime: '4 - 7 mins',
    currencyInStock: ['All Currencies Available'],
    features: ['Accessory Testing Bar', 'Phone Trade-In Instant Cash', 'eSIM Setup'],
    isAirport: false,
    lat: 55.8631,
    lng: -4.2519,
    googleMapsUrl: 'https://maps.google.com/?q=Buchanan+Galleries+220+Buchanan+St+Glasgow',
  },
];

// Generate 7-day or 30-day historical chart data for Recharts
export function generateHistoricalData(code: string, currentRate: number) {
  const data = [];
  const days = 7;
  const now = new Date();

  for (let i = days - 1; i >= 0; i--) {
    const d = new Date(now);
    d.setDate(d.getDate() - i);
    const dayLabel = d.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
    
    // Simulate slight daily fluctuation
    const randomVariation = (Math.sin(i * 1.5) * 0.008) + ((Math.random() - 0.5) * 0.005);
    const historicalRate = parseFloat((currentRate * (1 + randomVariation)).toFixed(code === 'JPY' || code === 'PKR' || code === 'INR' ? 2 : 4));
    
    data.push({
      date: dayLabel,
      rate: historicalRate,
      high: parseFloat((historicalRate * 1.003).toFixed(4)),
      low: parseFloat((historicalRate * 0.997).toFixed(4)),
    });
  }

  // Ensure last entry matches exact current rate
  data[data.length - 1].rate = currentRate;
  return data;
}
