import { Product } from './types';

export const FEATURED_PRODUCTS: Product[] = [
  // --- SMARTPHONES ---
  {
    id: 'iphone-16-pro-max',
    name: 'Apple iPhone 16 Pro Max',
    brand: 'Apple',
    category: 'smartphones',
    price: 1199.00,
    originalPrice: 1299.00,
    rating: 4.9,
    reviewsCount: 142,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
    badge: 'Flagship Deal',
    description: 'A18 Pro chip, Grade 5 Titanium design, Camera Control button, and 48MP Fusion Camera with 5x Telephoto lens.',
    specs: {
      Screen: '6.9" Super Retina XDR OLED',
      Processor: 'Apple A18 Pro',
      Camera: '48MP Main + 48MP Ultra Wide + 12MP 5x Telephoto',
      Battery: 'Up to 33 hours video playback',
      Warranty: '1 Year Wahla Store Guarantee',
    },
    colorVariants: [
      { name: 'Desert Titanium', hex: '#c5b49d', image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80' },
      { name: 'Natural Titanium', hex: '#a6a6a6', image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80' },
      { name: 'Black Titanium', hex: '#2b2b2e', image: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80' },
    ],
    storageOptions: ['256GB', '512GB', '1TB'],
    storagePrices: [
      { storage: '256GB', price: 1199.00, originalPrice: 1299.00 },
      { storage: '512GB', price: 1399.00, originalPrice: 1499.00 },
      { storage: '1TB', price: 1599.00, originalPrice: 1699.00 },
    ],
    inStock: true,
  },
  {
    id: 'samsung-s25-ultra',
    name: 'Samsung Galaxy S25 Ultra',
    brand: 'Samsung',
    category: 'smartphones',
    price: 1149.00,
    originalPrice: 1249.00,
    rating: 4.8,
    reviewsCount: 98,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80',
    badge: 'Galaxy AI Enabled',
    description: 'Snapdragon 8 Elite for Galaxy, built-in S Pen, 200MP camera system, and titanium frame.',
    specs: {
      Screen: '6.8" Dynamic AMOLED 2X 120Hz',
      Processor: 'Snapdragon 8 Elite',
      Camera: '200MP + 50MP + 50MP + 10MP',
      Battery: '5000mAh with 45W Fast Charge',
      Warranty: '1 Year Wahla Store Guarantee',
    },
    colorVariants: [
      { name: 'Titanium Gray', hex: '#777a80', image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80' },
      { name: 'Titanium Black', hex: '#212224', image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80' },
    ],
    storageOptions: ['256GB', '512GB', '1TB'],
    storagePrices: [
      { storage: '256GB', price: 1149.00, originalPrice: 1249.00 },
      { storage: '512GB', price: 1349.00, originalPrice: 1449.00 },
      { storage: '1TB', price: 1549.00, originalPrice: 1649.00 },
    ],
    inStock: true,
  },
  {
    id: 'google-pixel-9-pro',
    name: 'Google Pixel 9 Pro',
    brand: 'Google',
    category: 'smartphones',
    price: 899.00,
    originalPrice: 999.00,
    rating: 4.8,
    reviewsCount: 76,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
    badge: 'Best Camera AI',
    description: 'Tensor G4 processor, Gemini Advanced AI integration, Pro camera controls, and Super Actua display.',
    specs: {
      Screen: '6.3" Super Actua OLED 120Hz',
      Processor: 'Google Tensor G4',
      Camera: '50MP + 48MP Ultra + 48MP Telephoto',
      Battery: '4700mAh',
      Warranty: '1 Year Wahla Store Guarantee',
    },
    colorVariants: [
      { name: 'Obsidian Black', hex: '#1c1c1c', image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80' },
      { name: 'Porcelain White', hex: '#f0ece1', image: 'https://images.unsplash.com/photo-1546054454-aa26e2b734c7?auto=format&fit=crop&w=800&q=80' },
    ],
    storageOptions: ['128GB', '256GB', '512GB'],
    storagePrices: [
      { storage: '128GB', price: 899.00, originalPrice: 999.00 },
      { storage: '256GB', price: 999.00, originalPrice: 1099.00 },
      { storage: '512GB', price: 1149.00, originalPrice: 1249.00 },
    ],
    inStock: true,
  },

  // --- ACCESSORIES & CHARGERS ---
  {
    id: '65w-gan-travel-charger',
    name: 'Wahla Pro 65W GaN Universal Travel Charger',
    brand: 'Wahla Tech',
    category: 'chargers',
    price: 34.99,
    originalPrice: 49.99,
    rating: 4.9,
    reviewsCount: 215,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    badge: 'Travel Essential',
    description: 'Ultra-compact 65W GaN wall charger with interchangeable UK/EU/US/AU adapters and dual USB-C Power Delivery.',
    specs: {
      Output: '65W Max USB-C PD 3.0',
      Plugs: 'US / UK / EU / AU Slide-out Plugs',
      Ports: '2x USB-C + 1x USB-A',
      Safety: 'Over-voltage & thermal protection',
    },
    inStock: true,
  },
  {
    id: 'wahla-20k-100w-powerbank',
    name: 'Wahla Ultra 20,000mAh 100W Laptop & Phone Power Bank',
    brand: 'Wahla Tech',
    category: 'powerbanks',
    price: 49.99,
    originalPrice: 69.99,
    rating: 4.9,
    reviewsCount: 198,
    image: '/images/ultra_power_bank.jpg',
    badge: '100W Ultra Power',
    description: 'High-capacity 20,000mAh portable charger with 100W USB-C PD output to fast charge MacBooks, iPhones, Galaxies, and travel gear on the go.',
    specs: {
      Capacity: '20,000mAh Air-Travel Approved',
      Output: '100W USB-C Power Delivery Fast Output',
      Display: 'Smart Digital LED Battery % & Voltage Display',
      Ports: '2x USB-C + 1x USB-A',
    },
    inStock: true,
  },
  {
    id: 'universal-travel-plug-adapter',
    name: 'Wahla World Universal Travel Adapter & 4x USB Hub',
    brand: 'Wahla Tech',
    category: 'chargers',
    price: 24.99,
    originalPrice: 34.99,
    rating: 4.9,
    reviewsCount: 310,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    badge: '150+ Countries',
    description: 'All-in-one international power plug for UK, EU, USA, Japan, China, Australia, and Middle East with 4 USB charging ports.',
    specs: {
      Coverage: 'Works in 150+ Countries Worldwide',
      Fuse: 'Auto-Reset 8A Overload Safety Fuse',
      Ports: '3x USB-A + 1x USB-C PD 35W',
    },
    inStock: true,
  },

  // --- SEPARATED ADULT VAPES RETAIL (STRICTLY AGE 18+ ONLY) ---
  {
    id: 'crystal-pro-600-vape',
    name: 'Crystal Pro Max 600 Puffs Disposable Bar (18+)',
    brand: 'Crystal Bar',
    category: 'vapes',
    price: 5.99,
    originalPrice: 7.99,
    rating: 4.8,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=800&q=80',
    badge: '18+ Adult Retail Only',
    description: 'Compact 20mg nicotine salt disposable device. Strictly for existing adult smokers aged 18 and over in Glasgow store.',
    specs: {
      Nicotine: '20mg Nic Salt (2%)',
      Puffs: 'Approx 600 Puffs',
      Verification: 'Government Photo ID Required at Counter',
    },
    inStock: true,
    isAgeRestricted: true,
  },
  {
    id: 'elfbar-600-vape-pack',
    name: 'Elux Legend 3500 Mesh Pod System (18+)',
    brand: 'Elux',
    category: 'vapes',
    price: 11.99,
    originalPrice: 14.99,
    rating: 4.7,
    reviewsCount: 62,
    image: 'https://images.unsplash.com/photo-1563298723-dcfebaa392e3?auto=format&fit=crop&w=800&q=80',
    badge: '18+ Adult Retail Only',
    description: 'Rechargeable adult vape kit with dual mesh coil technology. In-store age verification required upon collection.',
    specs: {
      Nicotine: '20mg TPD Compliant',
      Battery: '650mAh Rechargeable Type-C',
      Verification: 'Strict Age 18+ Verification Enforced',
    },
    inStock: true,
    isAgeRestricted: true,
  },
];

export const PHONES_DATA: Product[] = FEATURED_PRODUCTS.filter((p) => p.category === 'smartphones');
export const ACCESSORIES_DATA: Product[] = FEATURED_PRODUCTS.filter((p) => p.category !== 'smartphones' && p.category !== 'vapes');
export const VAPES_DATA: Product[] = FEATURED_PRODUCTS.filter((p) => p.category === 'vapes');
export const PRODUCTS_DATA: Product[] = FEATURED_PRODUCTS;
