import { RemittanceCorridor, StoreBranch } from './types';

export const REMITTANCE_CORRIDORS: RemittanceCorridor[] = [
  {
    code: 'PKR',
    country: 'Pakistan',
    currencyCode: 'PKR',
    currencySymbol: 'Rs',
    flag: 'https://flagcdn.com/w80/pk.png',
    ratePerGbp: 364.50,
    feeGbp: 2.50,
    payoutMethods: ['Bank Deposit', 'Cash Pickup', 'Mobile Wallet'],
    estimatedTime: 'Same Day / Instant Bank Deposit',
    popular: true,
  },
  {
    code: 'INR',
    country: 'India',
    currencyCode: 'INR',
    currencySymbol: '₹',
    flag: 'https://flagcdn.com/w80/in.png',
    ratePerGbp: 109.80,
    feeGbp: 2.50,
    payoutMethods: ['Bank Deposit', 'Mobile Wallet'],
    estimatedTime: 'Instant UPI / Bank Deposit',
    popular: true,
  },
  {
    code: 'AED',
    country: 'United Arab Emirates',
    currencyCode: 'AED',
    currencySymbol: 'AED',
    flag: 'https://flagcdn.com/w80/ae.png',
    ratePerGbp: 4.75,
    feeGbp: 3.00,
    payoutMethods: ['Bank Deposit', 'Cash Pickup'],
    estimatedTime: 'Same Day Bank Transfer',
    popular: true,
  },
  {
    code: 'BDT',
    country: 'Bangladesh',
    currencyCode: 'BDT',
    currencySymbol: '৳',
    flag: 'https://flagcdn.com/w80/bd.png',
    ratePerGbp: 154.20,
    feeGbp: 2.50,
    payoutMethods: ['Bank Deposit', 'Cash Pickup', 'Mobile Wallet'],
    estimatedTime: 'Instant bKash / Bank Deposit',
    popular: true,
  },
  {
    code: 'PHP',
    country: 'Philippines',
    currencyCode: 'PHP',
    currencySymbol: '₱',
    flag: 'https://flagcdn.com/w80/ph.png',
    ratePerGbp: 74.80,
    feeGbp: 3.00,
    payoutMethods: ['Bank Deposit', 'Cash Pickup', 'Mobile Wallet'],
    estimatedTime: 'Same Day GCash / Bank Deposit',
    popular: true,
  },
  {
    code: 'NGN',
    country: 'Nigeria',
    currencyCode: 'NGN',
    currencySymbol: '₦',
    flag: 'https://flagcdn.com/w80/ng.png',
    ratePerGbp: 2020.00,
    feeGbp: 3.50,
    payoutMethods: ['Bank Deposit'],
    estimatedTime: 'Same Day Direct Bank Credit',
    popular: true,
  },
  {
    code: 'EUR',
    country: 'Eurozone (Europe)',
    currencyCode: 'EUR',
    currencySymbol: '€',
    flag: 'https://flagcdn.com/w80/eu.png',
    ratePerGbp: 1.182,
    feeGbp: 3.00,
    payoutMethods: ['Bank Deposit'],
    estimatedTime: 'SEPA Instant / Same Day',
    popular: true,
  },
  {
    code: 'USD',
    country: 'United States',
    currencyCode: 'USD',
    currencySymbol: '$',
    flag: 'https://flagcdn.com/w80/us.png',
    ratePerGbp: 1.302,
    feeGbp: 3.50,
    payoutMethods: ['Bank Deposit'],
    estimatedTime: 'ACH / Wire 1 Business Day',
    popular: true,
  },
];

export const REGULATORY_DETAILS = {
  companyName: 'Wahla Exchange Ltd',
  tradingName: 'Wahla Exchange',
  fcaAgentFrn: '1061169',
  principalName: 'Noble Travel and Money Exchange Ltd',
  principalFrn: '532990',
  fcaRegisterLink: 'https://register.fca.org.uk/s/search?q=1061169',
  principalFcaRegisterLink: 'https://register.fca.org.uk/s/search?q=532990',
  bureauPartner: 'Sia Trade Ltd',
  bureauHmrcReg: 'Registered with HMRC for Money Laundering Regulations (MLR) purposes',
  
  // Strict disclosures
  remittanceDisclosure: 'Money remittance services provided by Wahla Exchange Ltd as a registered agent of Noble Travel and Money Exchange Ltd, an FCA-authorised payment institution.',
  bureauDisclosure: 'Currency exchange services are provided through our bureau de change arrangements with Sia Trade Ltd, registered with HMRC for Money Laundering Regulations purposes.',
};

export const GLASGOW_BRANCH: StoreBranch = {
  name: 'Wahla Exchange Glasgow Main Branch',
  address: '22 Maxwell Road, Pollokshields',
  city: 'Glasgow',
  postcode: 'G41 1QE',
  phone: '+44 (0)141 266 0379',
  whatsapp: '+441412660379',
  email: 'info@wahlaexchange.co.uk',
  hours: {
    weekday: '09:30 AM - 06:30 PM',
    saturday: '10:00 AM - 06:00 PM',
    sunday: '11:00 AM - 04:00 PM',
  },
  services: [
    'International Money Remittance (Agent FRN 1061169)',
    'Foreign Currency Exchange (Bureau De Change)',
    'Mobile Phones & Tech Sales (WAHLA TECH)',
    'Vape & Accessories Counter (18+ Adult Retail)',
  ],
};

export const FREQUENT_QUESTIONS = [
  {
    q: 'How does Wahla Exchange provide money remittance services?',
    a: 'Wahla Exchange Ltd acts as a registered Payment Services Directive (PSD) agent (FCA FRN 1061169) of Noble Travel and Money Exchange Ltd, an FCA-authorised payment institution (FCA FRN 532990). All international money remittance transactions are processed under this authorized principal model.',
  },
  {
    q: 'How are foreign currency exchange (Bureau de Change) services provided?',
    a: 'Our foreign currency exchange (counter currency buying and selling) services are provided through our bureau de change arrangements with Sia Trade Ltd, which is registered with HMRC for Money Laundering Regulations (MLR) purposes.',
  },
  {
    q: 'What information and ID do I need to send money or exchange currency?',
    a: 'In accordance with UK Anti-Money Laundering (AML) standards, you will need a valid government-issued photo ID (Passport, UK Driving Licence, or EU ID card) and proof of address for transactions above statutory thresholds or upon request.',
  },
  {
    q: 'Can I lock an exchange rate online for counter pickup?',
    a: 'Yes. You can reserve foreign cash or lock in a remittance quote online. For foreign cash, you can generate a free counter pickup voucher with zero upfront payment required and collect at 22 Maxwell Road, Glasgow.',
  },
  {
    q: 'What fees apply to international money transfers?',
    a: 'Transfer fees depend on the destination country and transfer amount. Our online calculator shows the exact transfer fee, applied customer exchange rate, and recipient payout amount before you confirm any transfer.',
  },
  {
    q: 'How do I submit a formal complaint or inquiry?',
    a: 'We take customer feedback seriously. You can contact our compliance team in person at our Glasgow branch, via email at info@wahlaexchange.co.uk, or via our formal Complaints page. Remittance complaints are handled in accordance with our principal payment institution guidelines.',
  },
];
